import React from "react";

const MarketBody = () => {
  return (
    <section class="market-details pt-120 pb-120 position-relative z-0">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <h3 class="mb-7 mb-lg-8">
              Chart Analysis Mastery Reading the Language of the Markets
            </h3>
            <div class="market-details__card">
              <div class="market-details__thumbs position-relative">
                <img
                  src="assets/images/market_details.png"
                  alt="Image"
                  class="cus-rounded-2 w-100"
                />
              </div>
              <div class="market-details__content d-flex flex-column gap-5 gap-lg-6 mt-5 mt-lg-6">
                <p>
                  The Euro is down to 1.048, after ending yesterday at 1.0481.
                  Overall, a 0.01% loss or 1 pips today.
                </p>
                <p>
                  The MACD index is indicating that momentum is shifting from
                  bullish to bearish following a negative crossover. When the
                  MACD falls below the signal line, it is typically considered
                  to be a bearish development favoring short positions. On the
                  other hand, note that the Relative Strength Index has gone
                  below 30, going into oversold conditions and allowing more
                  gains. Euro-Dollar's lower Bollinger Band® is at 1.0476,
                  indicating that the asset has overextended to the downside and
                  could, therefore, bounce back as buyers look for bargains.
                </p>
                <p>
                  Overall, looking at the technical analysis landscape, it seems
                  that although indicators are mixed and some are pointing in
                  different directions further drawbacks may be next for the
                  Euro.
                </p>
                <p>
                  Positive performances can be seen by looking at other
                  currencies as GBP/NZD increases 0.19% to trade around 2.035.
                  EUR/NZD increases 0.18% to trade around 1.764.
                </p>
                <p>
                  n the meantime, USD/SGD trades close to 1.3734, with no major
                  change
                </p>
                <p>
                  The currency pair has been trending lower for about 2 months.
                  The Euro has shed 78.55% over the past three months.
                </p>
                <p>This content was generated by AI</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default MarketBody;
